<?php

$pays_par_groupe = [
    'Pays de l\'Europe' => [
        ['value' => 'DE', 'nom' => 'Allemagne'],
        ['value' => 'AT', 'nom' => 'Autriche'],
        ['value' => 'BE', 'nom' => 'Belgique'],
        ['value' => 'BG', 'nom' => 'Bulgarie'],
        ['value' => 'CY', 'nom' => 'Chypre'],
        ['value' => 'DK', 'nom' => 'Danemark'],
        ['value' => 'ES', 'nom' => 'Espagne'],
        ['value' => 'EE', 'nom' => 'Estonie'],
        ['value' => 'FI', 'nom' => 'Finlande'],
        ['value' => 'FR', 'nom' => 'France'],
        ['value' => 'GR', 'nom' => 'Grèce'],
        ['value' => 'HU', 'nom' => 'Hongrie'],
        ['value' => 'IE', 'nom' => 'Irlande'],
        ['value' => 'IT', 'nom' => 'Italie'],
        ['value' => 'LV', 'nom' => 'Lettonie'],
        ['value' => 'LT', 'nom' => 'Lituanie'],
        ['value' => 'LU', 'nom' => 'Luxembourg'],
        ['value' => 'MT', 'nom' => 'Malte'],
        ['value' => 'MC', 'nom' => 'Monaco'],
        ['value' => 'NL', 'nom' => 'Pays-Bas'],
        ['value' => 'PL', 'nom' => 'Pologne'],
        ['value' => 'PT', 'nom' => 'Portugal'],
        ['value' => 'RO', 'nom' => 'Roumanie'],
        ['value' => 'GB', 'nom' => 'Royaume-Uni'],
        ['value' => 'CZ', 'nom' => 'République tchèque'],
        ['value' => 'SK', 'nom' => 'Slovaquie'],
        ['value' => 'SI', 'nom' => 'Slovénie'],
        ['value' => 'SE', 'nom' => 'Suède'],
    ],
    'Les DOM-TOM' => [
        ['value' => 'TF', 'nom' => 'Antarctique'], // Terres Australes Françaises
        ['value' => 'GP', 'nom' => 'Guadeloupe'],
        ['value' => 'GF', 'nom' => 'Guyane francaise'],
        ['value' => 'MQ', 'nom' => 'Martinique'],
        ['value' => 'YT', 'nom' => 'Mayotte'],
        ['value' => 'NC', 'nom' => 'Nouvelle Calédonie'],
        ['value' => 'PF', 'nom' => 'Polynésie francaise'],
        ['value' => 'RE', 'nom' => 'Réunion (La)'],
        ['value' => 'PM', 'nom' => 'Saint Pierre et Miquelon'],
        ['value' => 'WF', 'nom' => 'Wallis et Futuna (Iles)'],
    ],
    'Les pays Hors UE' => [
        ['value' => 'AF', 'nom' => 'Afghanistan'],
        ['value' => 'ZA', 'nom' => 'Afrique du sud'],
        ['value' => 'AL', 'nom' => 'Albanie'],
        ['value' => 'DZ', 'nom' => 'Algérie'],
        ['value' => 'AD', 'nom' => 'Andorre'],
        ['value' => 'AO', 'nom' => 'Angola'],
        ['value' => 'AI', 'nom' => 'Anguilla'],
        ['value' => 'AQ', 'nom' => 'Antarctique'],
        ['value' => 'AG', 'nom' => 'Antigua et Barbuda'],
        ['value' => 'AW', 'nom' => 'Aruba'],
        ['value' => 'SA', 'nom' => 'Arabie saoudite'],
        ['value' => 'AR', 'nom' => 'Argentine'],
        ['value' => 'AM', 'nom' => 'Arménie'],
        ['value' => 'AW', 'nom' => 'Aruba'],
        ['value' => 'AU', 'nom' => 'Australie'],
        ['value' => 'AZ', 'nom' => 'Azerbaïdjan'],
        ['value' => 'BS', 'nom' => 'Bahamas'],
        ['value' => 'BH', 'nom' => 'Bahreïn'],
        ['value' => 'BD', 'nom' => 'Bangladesh'],
        ['value' => 'BB', 'nom' => 'Barbades'],
        ['value' => 'BZ', 'nom' => 'Belize'],
        ['value' => 'BM', 'nom' => 'Bermudes (Les)'],
        ['value' => 'BT', 'nom' => 'Bhoutan'],
        ['value' => 'BO', 'nom' => 'Bolivie'],
        ['value' => 'BA', 'nom' => 'Bosnie-Herzégovine'],
        ['value' => 'BW', 'nom' => 'Botswana'],
        ['value' => 'BV', 'nom' => 'Bouvet (Iles)'],
        ['value' => 'BN', 'nom' => 'Brunei Darussalam'],
        ['value' => 'BR', 'nom' => 'Brésil'],
        ['value' => 'BF', 'nom' => 'Burkina Faso'],
        ['value' => 'BI', 'nom' => 'Burundi'],
        ['value' => 'BY', 'nom' => 'Bélarus (Biélorussie)'],
        ['value' => 'BJ', 'nom' => 'Bénin'],
        ['value' => 'KH', 'nom' => 'Cambodge'],
        ['value' => 'CM', 'nom' => 'Cameroun'],
        ['value' => 'CA', 'nom' => 'Canada'],
        ['value' => 'CV', 'nom' => 'Cap Vert'],
        ['value' => 'KY', 'nom' => 'Cayman (Iles)'],
        ['value' => 'CL', 'nom' => 'Chili'],
        ['value' => 'CN', 'nom' => 'Chine'],
        ['value' => 'CX', 'nom' => 'Christmas (Ile)'],
        ['value' => 'CC', 'nom' => 'Cocos (Iles)'],
        ['value' => 'CO', 'nom' => 'Colombie'],
        ['value' => 'KM', 'nom' => 'Comores'],
        ['value' => 'CK', 'nom' => 'Cook (Iles)'],
        ['value' => 'KP', 'nom' => 'Corée du Nord'],
        ['value' => 'KR', 'nom' => 'Corée du Sud'],
        ['value' => 'CR', 'nom' => 'Costa Rica'],
        ['value' => 'CI', 'nom' => 'Cote d\'Ivoire'],
        ['value' => 'HR', 'nom' => 'Croatie'],
        ['value' => 'CU', 'nom' => 'Cuba'],
        ['value' => 'CW', 'nom' => 'Curaçao'],
        ['value' => 'DJ', 'nom' => 'Djibouti'],
        ['value' => 'DM', 'nom' => 'Dominique'],
        ['value' => 'EG', 'nom' => 'Egypte'],
        ['value' => 'SV', 'nom' => 'El Salvador'],
        ['value' => 'AE', 'nom' => 'Emirats Arabes Unis'],
        ['value' => 'EC', 'nom' => 'Equateur'],
        ['value' => 'ER', 'nom' => 'Erythrée'],
        ['value' => 'US', 'nom' => 'Etats-Unis'],
        ['value' => 'ET', 'nom' => 'Ethiopie'],
        ['value' => 'FK', 'nom' => 'Falkland (Ile)'],
        ['value' => 'FJ', 'nom' => 'Fidji (République des)'],
        ['value' => 'GA', 'nom' => 'Gabon'],
        ['value' => 'GM', 'nom' => 'Gambie'],
        ['value' => 'GH', 'nom' => 'Ghana'],
        ['value' => 'GI', 'nom' => 'Gibraltar'],
        ['value' => 'GD', 'nom' => 'Grenade'],
        ['value' => 'GL', 'nom' => 'Groenland'],
        ['value' => 'GU', 'nom' => 'Guam'],
        ['value' => 'GT', 'nom' => 'Guatemala'],
        ['value' => 'GG', 'nom' => 'Guernesey'],
        ['value' => 'GN', 'nom' => 'Guinée'],
        ['value' => 'GQ', 'nom' => 'Guinée Equatoriale'],
        ['value' => 'GW', 'nom' => 'Guinée-Bissau'],
        ['value' => 'GE', 'nom' => 'Géorgie'],
        ['value' => 'GS', 'nom' => 'Géorgie du Sud et Sandwich du Sud (Iles)'],
        ['value' => 'HT', 'nom' => 'Haïti'],
        ['value' => 'HM', 'nom' => 'Heard et McDonald (Iles)'],
        ['value' => 'HN', 'nom' => 'Honduras'],
        ['value' => 'HK', 'nom' => 'Hong Kong'],
        ['value' => 'UM', 'nom' => 'Iles Mineures éloignées des Etats-Unis'],
        ['value' => 'IN', 'nom' => 'Inde'],
        ['value' => 'ID', 'nom' => 'Indonésie'],
        ['value' => 'IQ', 'nom' => 'Irak'],
        ['value' => 'IR', 'nom' => 'Iran'],
        ['value' => 'IS', 'nom' => 'Islande'],
        ['value' => 'IL', 'nom' => 'Israel'],
        ['value' => 'JM', 'nom' => 'Jamaïque'],
        ['value' => 'JP', 'nom' => 'Japon'],
        ['value' => 'JE', 'nom' => 'Jersey'],
        ['value' => 'JO', 'nom' => 'Jordanie'],
        ['value' => 'KZ', 'nom' => 'Kazakhstan'],
        ['value' => 'KE', 'nom' => 'Kenya'],
        ['value' => 'KG', 'nom' => 'Kirghizistan'],
        ['value' => 'KI', 'nom' => 'Kiribati'],
        ['value' => 'KW', 'nom' => 'Koweït'],
        ['value' => 'BB', 'nom' => 'La Barbade'],
        ['value' => 'LA', 'nom' => 'Laos'],
        ['value' => 'LS', 'nom' => 'Lesotho'],
        ['value' => 'LB', 'nom' => 'Liban'],
        ['value' => 'LY', 'nom' => 'Libye'],
        ['value' => 'LR', 'nom' => 'Libéria'],
        ['value' => 'LI', 'nom' => 'Liechtenstein'],
        ['value' => 'MO', 'nom' => 'Macao'],
        ['value' => 'MK', 'nom' => 'Macédoine du Nord'],
        ['value' => 'MG', 'nom' => 'Madagascar'],
        ['value' => 'MY', 'nom' => 'Malaisie'],
        ['value' => 'MW', 'nom' => 'Malawi'],
        ['value' => 'MV', 'nom' => 'Maldives (Iles)'],
        ['value' => 'ML', 'nom' => 'Mali'],
        ['value' => 'MP', 'nom' => 'Mariannes du Nord (Iles)'],
        ['value' => 'MA', 'nom' => 'Maroc'],
        ['value' => 'MH', 'nom' => 'Marshall (Iles)'],
        ['value' => 'MU', 'nom' => 'Maurice'],
        ['value' => 'MR', 'nom' => 'Mauritanie'],
        ['value' => 'MX', 'nom' => 'Mexique'],
        ['value' => 'MD', 'nom' => 'Moldavie'],
        ['value' => 'MN', 'nom' => 'Mongolie'],
        ['value' => 'ME', 'nom' => 'Montenegro'],
        ['value' => 'MS', 'nom' => 'Montserrat'],
        ['value' => 'MZ', 'nom' => 'Mozambique'],
        ['value' => 'MM', 'nom' => 'Myanmar'],
        ['value' => 'NA', 'nom' => 'Namibie'],
        ['value' => 'NR', 'nom' => 'Nauru'],
        ['value' => 'NP', 'nom' => 'Népal'],
        ['value' => 'NI', 'nom' => 'Nicaragua'],
        ['value' => 'NE', 'nom' => 'Niger'],
        ['value' => 'NG', 'nom' => 'Nigeria'],
        ['value' => 'NU', 'nom' => 'Niué'],
        ['value' => 'NF', 'nom' => 'Norfolk (Iles)'],
        ['value' => 'NO', 'nom' => 'Norvège'],
        ['value' => 'NZ', 'nom' => 'Nouvelle-Zélande'],
        ['value' => 'OM', 'nom' => 'Oman'],
        ['value' => 'UG', 'nom' => 'Ouganda'],
        ['value' => 'UZ', 'nom' => 'Ouzbékistan'],
        ['value' => 'PK', 'nom' => 'Pakistan'],
        ['value' => 'PW', 'nom' => 'Palau'],
        ['value' => 'PA', 'nom' => 'Panama'],
        ['value' => 'PG', 'nom' => 'Papouasie Nouvelle-Guinée'],
        ['value' => 'PY', 'nom' => 'Paraguay'],
        ['value' => 'PH', 'nom' => 'Philippines'],
        ['value' => 'PN', 'nom' => 'Pitcairn (Iles)'],
        ['value' => 'PR', 'nom' => 'Porto Rico'],
        ['value' => 'PE', 'nom' => 'Pérou'],
        ['value' => 'QA', 'nom' => 'Qatar'],
        ['value' => 'RU', 'nom' => 'Russie'],
        ['value' => 'RW', 'nom' => 'Rwanda'],
        ['value' => 'DO', 'nom' => 'République Dominicaine'],
        ['value' => 'CD', 'nom' => 'République Démocratique du Congo'],
        ['value' => 'CF', 'nom' => 'République centrafricaine'],
        ['value' => 'EH', 'nom' => 'Sahara Occidental'],
        ['value' => 'VC', 'nom' => 'Saint Vincent et les Grenadines'],
        ['value' => 'KN', 'nom' => 'Saint-Kitts et Nevis'],
        ['value' => 'SM', 'nom' => 'Saint-Marin'],
        ['value' => 'VA', 'nom' => 'Saint-Siège (Cité du Vatican)'],
        ['value' => 'SH', 'nom' => 'Sainte Hélène'],
        ['value' => 'LC', 'nom' => 'Sainte Lucie'],
        ['value' => 'WS', 'nom' => 'Samoa'],
        ['value' => 'ST', 'nom' => 'Sao Tomé et Principe (Rép.)'],
        ['value' => 'RS', 'nom' => 'Serbie'],
        ['value' => 'SC', 'nom' => 'Seychelles'],
        ['value' => 'SL', 'nom' => 'Sierra Leone'],
        ['value' => 'SG', 'nom' => 'Singapour'],
        ['value' => 'SO', 'nom' => 'Somalie'],
        ['value' => 'SD', 'nom' => 'Soudan'],
        ['value' => 'LK', 'nom' => 'Sri Lanka'],
        ['value' => 'CH', 'nom' => 'Suisse'],
        ['value' => 'SR', 'nom' => 'Suriname'],
        ['value' => 'SJ', 'nom' => 'Svalbard et Jan Mayen (Iles)'],
        ['value' => 'SZ', 'nom' => 'Swaziland (Eswatini)'],
        ['value' => 'SY', 'nom' => 'Syrie'],
        ['value' => 'SN', 'nom' => 'Sénégal'],
        ['value' => 'TJ', 'nom' => 'Tadjikistan'],
        ['value' => 'TZ', 'nom' => 'Tanzanie'],
        ['value' => 'TW', 'nom' => 'Taïwan'],
        ['value' => 'TD', 'nom' => 'Tchad'],
        ['value' => 'IO', 'nom' => 'Territoire britannique de l\'océan Indien'],
        ['value' => 'PS', 'nom' => 'Territoires Palestiniens'],
        ['value' => 'TH', 'nom' => 'Thaïlande'],
        ['value' => 'TL', 'nom' => 'Timor-Leste'],
        ['value' => 'TG', 'nom' => 'Togo'],
        ['value' => 'TK', 'nom' => 'Tokelau'],
        ['value' => 'TO', 'nom' => 'Tonga'],
        ['value' => 'TT', 'nom' => 'Trinité et Tobago'],
        ['value' => 'TN', 'nom' => 'Tunisie'],
        ['value' => 'TM', 'nom' => 'Turkménistan'],
        ['value' => 'TC', 'nom' => 'Turks et Caïques (Iles)'],
        ['value' => 'TR', 'nom' => 'Turquie'],
        ['value' => 'TV', 'nom' => 'Tuvalu'],
        ['value' => 'UA', 'nom' => 'Ukraine'],
        ['value' => 'UY', 'nom' => 'Uruguay'],
        ['value' => 'VU', 'nom' => 'Vanuatu'],
        ['value' => 'VG', 'nom' => 'Vierges britanniques (Iles)'],
        ['value' => 'VI', 'nom' => 'Vierges américaines (Iles)'],
        ['value' => 'VN', 'nom' => 'Viet Nam'],
        ['value' => 'VE', 'nom' => 'Vénézuela'],
        ['value' => 'YE', 'nom' => 'Yémen'],
        ['value' => 'ZM', 'nom' => 'Zambie'],
        ['value' => 'ZW', 'nom' => 'Zimbabwe'],
        ['value' => 'FM', 'nom' => 'États Fédérés de Micronésie'],
        ['value' => 'IM', 'nom' => 'Île de Man'],
        ['value' => 'SB', 'nom' => 'Îles Salomon'],
    ]
];

return $pays_par_groupe;